---
- name: Install MySQL depden
  command: amazon-linux-extras install epel -y

- name: Install mysql
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start service mysql, if not started
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

