---
- name: Install Tomcat 
  yum:
    name: tomcat
    state: latest
   
- name: Deploy yuva war file in Tomcat
  copy:
    src: "{{ item }}"
    dest: /usr/share/tomcat/webapps/
    owner: tomcat
    group: tomcat
    mode: '0755'
  with_fileglob:
    - /var/jenkins_home/workspace/TomcatDeployment/javaweb/WebContent/*.war    
    
- name: Start service tomcat, if not started
  ansible.builtin.service:
    name: tomcat
    state: started
