---
- name: Install Tomcat 
  yum:
    name: tomcat
    state: latest

   
- name: Deploy yuva war file in Tomcat
  ansible.builtin.copy:
    src: /var/jenkins_home/workspace/JavaWeb/javaweb/hello.war
    dest: /usr/share/tomcat/webapps/
    owner: tomcat
    group: tomcat
    mode: '0755'
    
- name: Start service tomcat, if not started
  ansible.builtin.service:
    name: tomcat
    state: started
